# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171028_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
