# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configtables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Venue Type',
                'verbose_name_plural': 'Venue Types',
                'ordering': ['vt_name'],
            },
        ),
    ]
