# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20171028_1200'),
        ('configtables', '0002_venuetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('code', models.CharField(choices=[('nn', 'None'), ('mr', 'Minor'), ('sr', 'Serious'), ('cr', 'Critical')], default='nn', max_length=2)),
                ('description', models.TextField(verbose_name='Description')),
                ('is_athlete_involved', models.BooleanField(default=False, verbose_name='Involves an Athlete')),
                ('functional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incidents', to='configtables.FunctionalArea', verbose_name='Functional Area')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incidents', to='events.Venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1)),
            ],
        ),
    ]
